title: Tools Examencommissie IICT - HU
description: Tools Examencommissie IICT - HU
url: "https://hu-iict-ec.github.io"
baseurl: "" 

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle

tools:
  - Examinator_Excel_Download.html
  - Steekproef.html
  # Add more tool include filenames here